### PR TITLE
Add validation column for threat models

### PR DESCRIPTION
**Pull request by gowthamsk-arm**
Signed-off-by: Gowtham Suresh Kumar <gowtham.sureshkumar@arm.com>

### CODE REVIEW

**Review by ionut-arm — COMMENTED** [review]
What's the difference between `N/A` and `-`?

**Comment by gowthamsk-arm** [comment]
`N/A` is for test cases that are out of scope for Parsec testing. We have tickets created for tests with `-`. These will be added in future and updated in the book.

**Comment by ionut-arm** [comment]
> We have tickets created for tests with -

Could you use a link to those tickets instead of `-`?

**Comment by gowthamsk-arm** [comment]
Not required.

**Pull request closed without merging**
