### PR TITLE
Added PsaExportKey and tweaked opcodes for asymmetric encrypt and decrypt

### PR DESCRIPTION
**Pull request by sbailey-arm**
Added link to `SUMMARY.md`.

Signed-off-by: Samuel Bailey <samuel.bailey@arm.com>

### CODE REVIEW

**Comment by sbailey-arm** [comment]
> 
> 
> > and tweaked opcodes for asymmetric encrypt and decrypt
> 
> did you keep the commit message from the last commit?

Yes, I amended the previous commit

> 
> 
> > and tweaked opcodes for asymmetric encrypt and decrypt
> 
> did you keep the commit message from the last commit?

Yep, realised that's not a good idea for a new PR so I've changed it.

**Comment by ionut-arm** [comment]
I'm curious why [this](https://parallaxsecond.github.io/parsec-book/parsec_client/operations/psa_export_key.html) is happening, though

**Comment by sbailey-arm** [comment]
> 
> 
> I'm curious why [this](https://parallaxsecond.github.io/parsec-book/parsec_client/operations/psa_export_key.html) is happening, though

That's weird. I think I ran into something like that before and presumed the compiler was optimising the page away as there were no links. But there _are_ other links to it so that should not be happening.

**Comment by ionut-arm** [comment]
It might be optimising away pages that are no referred to from the Summary :] we'll just have to wait and see

**Pull request merged**
